
---

plugins:
  - import
  - jest

env:
  node: true
  jest: true

parser: babel-eslint

extends:
  - 'airbnb-base'

rules:
  no-console: 0
  no-underscore-dangle:  ["error", { "allow": ["__filename", "__dirname"] }]
  import/extensions: off